apiVersion: batch/v1
kind: CronJob
metadata:
  name: django-clearsessions
spec:
  schedule: "0 3 * * *"
  startingDeadlineSeconds: 3600
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 300
      backoffLimit: 1
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: django
              image: django_app:latest
              imagePullPolicy: IfNotPresent
              command: ["./manage.py"]
              args: ["clearsessions"]
              envFrom:
                - secretRef:
                    name: django