apiVersion: v1
kind: Service
metadata:
  name: django
  namespace: edu-aleksandr-babynin
  labels:
    app.kubernetes.io/name: django
    app.kubernetes.io/part-of: django-site
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: django
  ports:
    - name: http
      port: 80
      targetPort: http
