apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2026-06-03T17:45:07Z"
  finalizers:
  - ingress.ya.ru/final
  name: main-nginx
  namespace: edu-aleksandr-babynin
  resourceVersion: "260436470"
  uid: 88466b19-8332-4a3d-9b32-45135c1cb4c0
spec:
  clusterIP: 10.96.248.76
  clusterIPs:
  - 10.96.248.76
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30223
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: main-nginx
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
