apiVersion: v1
kind: ConfigMap
metadata:
  name: main-nginx-config
  namespace: edu-aleksandr-babynin
  labels:
    app.kubernetes.io/name: main-nginx
    app.kubernetes.io/part-of: django-site
data:
  nginx.conf: |
    user nginx;
    worker_processes 2;

    events {
      worker_connections 10240;
    }

    http {
      server {
        listen 80;
        server_name localhost;

        location / {
          proxy_pass http://django:80;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
        }
      }
    }
